on:
  issues:
    types: [opened]
jobs:
  github-actions-automate-projects:
    runs-on: ubuntu-latest
    steps:       
    - name: add-new-issues-to-repository-based-project-column
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      if: github.event_name == 'issues' && contains(github.event.issue.title, 'Episode Suggestion')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/chrisreddington/cloudwithchris.com/projects/1
        GITHUB_PROJECT_COLUMN_NAME: To do
