on:
  workflow_dispatch:
jobs:
  run_google_analytics:
    permissions:
      id-token: write
      contents: read
    uses: CloudWithChris/Reusable-Workflows/.github/workflows/google-analytics-top-pages.yaml@main
    with:
      script_path: ".github/workflows/scripts/google-analytics.js"
    secrets:
      GH_GOOGLE_FED_PROVIDER: ${{ secrets.GH_GOOGLE_FED_PROVIDER }}
      GA_API_SERVICE_ACC_EMAIL: ${{ secrets.GA_API_SERVICE_ACC_EMAIL }}
      GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}