name: 'Close Preview Branch'
on:
  pull_request:
    branches: 
      - dev
    types: 
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:     
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}     
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az storage blob delete-batch --account-name cloudwithchrispreview -s '$web' --pattern '${{ github.head_ref }}/*'
